branches:
  only:
    - master

git:
  depth: 10

matrix:
  include:
    - os: linux
      language: python
      env: ATOM_CHANNEL=stable
    - os: linux
      language: python
      env: ATOM_CHANNEL=beta
    - os: osx
      language: generic
      env: ATOM_CHANNEL=stable
      before_install:
        - brew update
        - brew install python
    - os: osx
      language: generic
      env: ATOM_CHANNEL=beta
      before_install:
        - brew update
        - brew install python

install:
  - pip install pyflakes

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change
